### ISSUE TITLE
[조사] 이미지 전처리 방법 

### ISSUE THREAD

**Issue by Junuu** [suimn416/2019.Spring.AI_Leader#11]
이미지 전처리: 학습을 진행하기 전에 학습의 대상이 될 이미지를 분류하고 선별하는 작업
컴퓨터는 이미지를 보고 사람처럼 바로 인식하지 못합니다.
따라서 이미지를 인식할 수 있도록 전 처리 과정이 필요합니다.

전처리의 과정
예시)
웹에서 개, 고양이 이미지를 Crawling(크롤링) 하였을 때
1.	저장된 이미지를 정사각형 형태의 크기로 조정한후 새로운 폴더에 저장합니다.
2.	사이즈가 조정된 32x32x3 형태를 한 장당 1x3072 형태로 csv로 저장합니다. (Height 32, Weight 32, RGB 3)
3.	CSV로 저장된 파일을 불러와 Training, Test, validation set으로 나눕니다.
4.	Zero-center를 맞춰 주기 위해 각각 데이터 셋에 대하여 전체의 평균 값을 빼 줍니다.
출처: https://www.slideshare.net/leeyuseong1/ss-90727307

OpenCV를 이용한 영상 이진화 
만약에 밝기 변화에도 이미지가 잘 분석되게 하고 싶다면 OpenCV를 활용하여 이진화 시킨다면 괜찮은 방법일 것 같음.
출처: https://webnautes.tistory.com/1034

Google Landmark Retrieval Challenge의 Data Set(구글의 데이터 셋)
사진이 JPG, PNG가 아닌 URL로 되어있습니다.
출처:
https://www.kaggle.com/c/landmark-retrievalchallenge/data
https://www.kaggle.com/google/google-landmarks-dataset#boxes_split1.csv

-케라스를 이용하여 사진(jpg, png 등) 파일을 딥러닝 학습을 위한 데이터로 만드는 방법
출처: https://blog.naver.com/cjsdyd2000/221226971713

#

**Comment by unizard** [comment]
@Junuu 상황에때라서 학습용으로 구글 랜드마크 데이터 셋을쓰게 될지도 모르면 미리 url기반으로 크롤링을 시도하는 것을 듯...단지 용량이 많이 크니까 이점 고려들하렴
