### ISSUE TITLE
[예상] 최종결과물

### ISSUE THREAD

**Issue by socome** [suimn416/2019.Spring.AI_Leader#2]
![최종결과물](https://user-images.githubusercontent.com/44772344/56336537-d58c8900-61db-11e9-95f8-3662869fb018.png)

**Comment by unizard** [comment]
@socome  지금 예시로 든 사진의 케이스는 엄청! 어려운 케이스 모음인데? 이거 되면 대박 :)
1. 밝기변화가 심함 (brightness change)
2. 시점변화가 심함 (viewpoint change)
