### ISSUE TITLE
[조사] 딥러닝 네트워크 분류기

### ISSUE THREAD

**Issue by Namhyunho** [suimn416/2019.Spring.AI_Leader#6]
이미지 분류및 자동 주석
https://www.cv-foundation.org/openaccess/content_cvpr_2015/html/Wu_Deep_Multiple_Instance_2015_CVPR_paper.html

이미지 검색 
https://www.cv-foundation.org/openaccess/content_cvpr_workshops_2015/W03/html/Lin_Deep_Learning_of_2015_CVPR_paper.html

**Comment by unizard** [comment]
@Namhyunho 
밑에 지원이도 조사했지만 잘정리된 곳이 있어공유드림
https://github.com/kobiso/Computer-Vision-Leaderboard
