### ISSUE TITLE
Google landmark Recognition/Retrieval 성능지표 

### ISSUE THREAD

**Issue by socome** [suimn416/2019.Spring.AI_Leader#8]
Google landmark Recognition

![평가지표 _ Recognition](https://user-images.githubusercontent.com/44772344/56877095-9a654200-6a86-11e9-9dc4-aa66a6ea6656.PNG)

Google landmark Retrieval

![평가지표 _ Retrieval](https://user-images.githubusercontent.com/44772344/56877083-8b7e8f80-6a86-11e9-9c48-c4aa678b6c9d.PNG)

**Comment by unizard** [comment]
@socome 두 task 는 서로 지향점이 달라서 어느쪽으로 할지 정해야 할듯한데... 일단 아래로 시도?
